### ISSUE TITLE
Rewrite copy-to as Readable

### ISSUE THREAD

**Issue by pspi** [brianc/node-pg-copy-streams#104]
Extracting this from PR https://github.com/brianc/node-pg-copy-streams/pull/103

> In the future, we might want to extend copy-to out of Readable and not Transform which will avoid giving users duplex streams when the reality is copy-to = readable, copy-from = writable.

The copy-from side is now a Writable (https://github.com/brianc/node-pg-copy-streams/pull/102). For symmetry, it'd be good if copy-to was a Readable (it's currently a Transform stream.)

**Comment by jeromew** [comment]
a PR for this can be found on #105

**Comment by jeromew** [comment]
in version 5.0.0 copy-to extends `Readable`

**Comment by jeromew** [comment]
in version 5.0.0 copy-to extends `Readable`
