### ISSUE TITLE
Issue with archiver and larger files

### ISSUE THREAD

**Issue by pieterprovoost** [brianc/node-pg-copy-streams#107]
I'm trying to copy to a zip file using https://www.npmjs.com/package/archiver. This works fine and almost instantaneous for smaller datasets, but for anything over 30MB or so the code below hangs indefinitely.

```js
const archiver = require("archiver");
const copyTo = require("pg-copy-streams").to;
const pgp = require("pg-promise");

const addFile = function(readStream, archive, filename) {
    return new Promise((resolve, reject) => {
        archive.append(readStream, { name: filename });
        readStream.on("end", resolve);
        readStream.on("error", reject);
    });
};

const download = async function(res) {

    // ...

    const archive = archiver("zip");
    const con = await db.connect();
    const client = con.client;
    const dataStream = client.query(copyTo("copy (" + dataQuery + ") to stdout with csv delimiter ',' header"));
    await addFile(dataStream, archive, "test.csv");
    res.attachment("test.zip");
    archive.pipe(res);
    archive.finalize();

}
```

Thanks!

**Comment by jeromew** [comment]
thanks for the report.
I do not understand what is `res` in your code.

could you try to simplify the test you have so that it could be reproduced more easily ?
I'd suggest for example using
dataQuery = `select repeat('-', ${Math.pow(2,10)}) from generate_series(1, ${Math.pow(2,20})`

**Comment by jeromew** [comment]
I suspect that by writing 

    await addFile(dataStream, archive, "test.csv");

and 

    readStream.on("end", resolve);

this way you create some kind of lock problem in the piping mechanism

can you try removing the await ?

**Comment by pieterprovoost** [comment]
Thanks, removing `await` did the trick. I had it there because I'm adding multiple files and wanted to wait for before cleaning up the database connection, I'll need to figure out how to handle that.

`res` is the Express response object.

**Comment by jeromew** [comment]
I tested with success with very large output with

````js
const pg = require('pg')
const archiver = require('archiver')
const CopyOut = require('./index.js').to
const fs = require('fs')

async function asyncCall() {

  const archive = archiver("zip");
  const client = new pg.Client()
  await client.connect()
  const copyOut = CopyOut(`COPY (select repeat('-', ${Math.pow(2,10)}) from generate_series(1, ${Math.pow(2,20)})) TO STDOUT`)
  copyOut.on('end', ()=> {
    client.end()
  })
  const dataStream = client.query(copyOut)
  archive.append(dataStream, { name: "test.csv" });
  archive.pipe(fs.createWriteStream('test.zip'))
  archive.finalize()
}

asyncCall()
````

can you test it ?

The problem I think is that with `await addFile(dataStream, archive, "test.csv");` you block the call to `archive.pipe(res);` from happening until the `readStream` is fully read (`end` event). This is very bad for streaming performance and can trigger a backpressure issue or a memory issue or maybe some other issue inside `archiver`. The `archiver` API has an internal queue and you do not need to wait for the file to `end`.

keep me posted on your results.

**Comment by pieterprovoost** [comment]
Great, based on your feedback I tried calling `archive.pipe(res)` before `await addFile()` and all seems to be well now!
