### ISSUE TITLE
Question:how to wait until the copy is completely done

### ISSUE THREAD

**Issue by agorina** [brianc/node-pg-copy-streams#108]
I am using Node 12.9 and  "pg-copy-streams": "^5.1.0".

Here is how I do "COPY":
```
export const sqlCopy = async (file: string, table: string, fields: string[]) => {
        const client = await pool.connect()
        const readSteam = fs.createReadStream(file)
        const copyStream = client.query(copyFrom(`COPY ${table} (${fields.join(',')}) FROM STDIN CSV HEADER`))

        copyStream.on('finish', () => {
            client.release()
            debugLog(`Completed copying ${file} into  ${table}`)
        })
        await readSteam.pipe(copyStream)
}
```

The calling function has a list of promises that it waits for:
```
   public async loadData(fieldSpecs: FieldSpec[]) {
        const promises: Promise<any>[] = []
        fieldSpecs.filter(spec => spec.load).map(pack => {
            promises.push(sqlCopy(pack.file, pack.table, pack.fields))
        })

        await Promise.all(promises)
            //TODO: how to get this done after all Copy is done
            .then(() => debugLog(`Done`))
            .catch((e) => {
                debugLog(`Error in runCopyFrom with: ${e}`)
            })
    }
```

I run 30 files and the logs show `Done` before some of the `Completed copying ...`

Currently I load files in parallel, but I would like to chain them sequentially. In this case the problem becomes more concerning.

What am I doing wrong?

**Comment by jeromew** [comment]
Hello,
thanks for the report.

I am not familiar with the guarantees given by `await readSteam.pipe(copyStream)`

most probably what happens is that your `sqlCopy` does not wait until the COPY operation is finished.

this following code is not handling error cases, but for a start you could try

````js
export const sqlCopy = async (file: string, table: string, fields: string[]) => {
        const client = await pool.connect()
        const readSteam = fs.createReadStream(file)
        const copyStream = client.query(copyFrom(`COPY ${table} (${fields.join(',')}) FROM STDIN CSV HEADER`))
        readSteam.pipe(copyStream)
        await once(copyStream, 'finish')
        client.release()
        debugLog(`Completed copying ${file} into  ${table}`)
}
````
this is using https://nodejs.org/api/events.html#events_events_once_emitter_name

error handling could probably be done using `pipeline` or `finished` from the stream module.

**Comment by agorina** [comment]
This works! Thank you very much for the quick response.
