### ISSUE TITLE
Question: Copy From file format support 

### ISSUE THREAD

**Issue by AmitKulkarni9** [brianc/node-pg-copy-streams#123]
Did you know that PostgreSQL supports streaming binary data directly into and out of a table? This means you can take your favorite CSV or TSV or whatever format file and pipe it directly into an existing PostgreSQL table.

What does it mean "whatever format file" does it support Json file ? 

It says here (https://www.postgresql.org/docs/current/sql-copy.html)
FORMAT
Selects the data format to be read or written: text, csv (Comma Separated Values), or binary. The default is text.

**Comment by jeromew** [comment]
Hello,

when you build a pipeline, you have something like

source => transform into a FORMAT compatible stream (csv, tsv) => postgres

so if your source is json, you will need to add an intermediate stream transformation that will transform your json into a csv for example.

there is another module for the binary format but this is more advanced.

do you think we should modify this sentence to be more clear ? How would you write it ?

**Comment by AmitKulkarni9** [comment]
Thanks Jeromew for replying. 

What I understand is PostgreSQL supports text, csv/tsv and binary. So for example if you have data in another format (say JSON) convert it to one of the above i.e., text, csv/tsv or binary and pipe it to PostgreSQL. 

For your question how to write it and be clear. What do you think of below text:

PostgreSQL supports file format of text, csv/tsv and binary data.  If you have data in another format (say for example JSON) convert it to one of the supported format i.e., text, csv/tsv or binary and pipe it directly into an existing PostgreSQL table.

**Comment by jeromew** [comment]
Thanks I modified the README.md to make it a bit more clear - https://github.com/brianc/node-pg-copy-streams/commit/b3436748e6d4541b2ef8249125f37402a41da97c
