### ISSUE TITLE
second example is misleading

### ISSUE THREAD

**Issue by rcreasi-visitrend** [brianc/node-pg-copy-streams#13]
In the second example (pipe from a file to table) you attach an event listener to `fileStream`:    

    fileStream.on('error', done);

But that doesn't capture errors and an exception is thrown. When I instead attach the listener to the `stream` object, everything is cool. 

I found it's also preferable to listen for an 'end' event on `stream` because that event isn't emitted in the case of error (`fileStream` still does emit an 'end' event).

**Comment by jeromew** [comment]
I think the documentation has been updated since Jul 2014 with more listeners in the second example. Closing.
