### ISSUE TITLE
copyFrom stream's end function does not behave as expected

### ISSUE THREAD

**Issue by prabhash-c** [brianc/node-pg-copy-streams#130]
I have this pseudo-code that illustrates the issue I am facing

```javascript
let readStream ( a read stream from somewhere )
var stream = client.query(copyFrom('COPY my_table FROM STDIN'))

readStream.on('data', (d) => stream.write(d))
readStream.on('finish', () =>  stream.end() )
stream.on('error', (e) => console.log(e))
```

When I am trying to close the stream on the 'finish' event of the readStream, it errors out with a message from pg module itself

```console
Error: Connection terminated
    at Connection.<anonymous> (/Users/path/to/code/node_modules/pg/lib/client.js:132:36)`
```
and the data is not written on the PG table. Is this a flaw or am I missing something? 

Thanks a ton for your help!

**Comment by prabhash-c** [comment]
I need to do some checking and transforming, and the input stream has a method to send individual records, that I need to use.

How do I indicate to the stream that it can end and no more data is coming? `stream.end()` seems like what is needed?

**Comment by jeromew** [comment]
copyFrom STDIN is a standard Writable stream so yes `stream.end()` is a way to indicate to the stream that no more data is coming.

The error message you have `Error: Connection terminated` seems to mean that your pg connection was closed by something (?) It should not be closed before the 'finish' event is received on the copyFrom stream.

**Comment by prabhash-c** [comment]
Okay, so it seems `stream.end()` triggers `stream.on('error', (e) => console.log(e))` which was breaking my promise chain resulting in connection being terminated. 

If there any logical reason why `stream.end()` triggers `stream.on.('error')` for pg-copy-stream

**Comment by jeromew** [comment]
the only reason I could see is if you close the pg connection before `finish` triggers on copyFrom. If you do that, you close the connection while the COPY operation is not yet finished.

apart from that, if you need more help, please write a reproducible test highlighting your problem.
