### ISSUE TITLE
Cannot execute multiple COPY commands within the same transaction

### ISSUE THREAD

**Issue by dylanplural** [brianc/node-pg-copy-streams#132]
Given the following pattern:

```js
await client.query('BEGIN')
const reader = client.query(to('...'))
const writer = client.query(from('...'))
reader.pipe(writer)


await new Promise(
  resolve => {
    reader.once('end', () => writer.end())
    resolve()
  }
)

const reader2 = client.query(to('...'))
const writer2 = client.query(from('...'))
reader2.pipe(writer2)

await new Promise(
  resolve => {
    reader2.once('end', () => writer2.end())
    resolve()
  }
)

await client.query('COMMIT')
```

The first query will execute correctly, the second will hang.
It appears there is a constraint that I must call "client.release()" between each copy query, I cannot maintain the same transaction and execute multiple COPY queries within it.

**Comment by jeromew** [comment]
Hello, thanks for the report.
can you create a test in the test directory that reproduces the problem without pseudo code ?

**Comment by dylanplural** [comment]
Wrote that test - in the process I discovered the actual bug was related to other code that happened between the two transactions.

Specifically related to running both a DROP and a CREATE in parallel transactions that resulted in a lock that was never released. Closing this 👍
