### ISSUE TITLE
copyFrom: TypeError: this.cb_ReadyForQuery is not a function

### ISSUE THREAD

**Issue by Robouste** [brianc/node-pg-copy-streams#155]
I'm getting this error when trying to execute a COPY.

`TypeError: this.cb_ReadyForQuery is not a function`

```typescript
import { Pool } from "pg";
import { from as copyFrom } from "pg-copy-streams";

...

const import = (await readFile("./download/import.sql")).toString();

const pool = new Pool({
  user: "postgres",
  host: "localhost",
  database: "database",
  password: "password",
  port: 5432,
});

const split = import.split("\n");

for await (const line of split) {
  if (line === "") {
    continue;
  }

  await pool.query(copyFrom(line.replace("\\copy", "COPY")));
}
```

When I try using Client instead of Pool, it hangs indefinitely without any errors.

Here is an example of a line:
`\copy wikidata from 'absolute/path/to/file/wikidata'`

If I don't replace \copy with COPY, I get this: `error: syntax error at or near "\"`

**Comment by jeromew** [comment]
Hello,
thanks for your report.

I don't totally understand what it is you are trying to do.

can you give me a reference or copy the first few lines of `./download/import.sql` and a link to this file so I can download it ?

it seems that you are trying to inject an sql file that is a dump of a table with a `COPY wikidata from 'absolute/path/to/file/wikidata'` but this module is used for scenarios when COPY is used FROM STDIN to TO STDOUT.

why don't you inject it with classical pg tools for ingesting sql dump files ?

**Comment by Robouste** [comment]
Thanks for the quick reply.

Here is the full content of the import.sql:

> \copy anime from 'R:\Dev\download\db\anime'
> \copy chars from 'R:\Dev\download\db\chars'
> \copy chars_traits from 'R:\Dev\download\db\chars_traits'

Indeed I'm trying to copy data from a simple text file formated like this:
`id	type 	support 	year 	other	title`

So I guess I can't achieve it with this plugin.

> why don't you inject it with classical pg tools for ingesting sql dump files ?

What do you mean? I'm new to this and I've been struggling the whole day :)

**Comment by jeromew** [comment]
I believe the dump you have can be restored with `psql` which is a classic postgres tool.
cf https://www.postgresql.org/docs/16/backup-dump.html in the "restoring a dump" section.

**Comment by Robouste** [comment]
Yeah indeed, I first tried with psql but I got stuck because I can't set the password programmaticaly. [More info here.](https://stackoverflow.com/questions/77469166/nodejs-trying-to-execute-postgre-sql-file?noredirect=1#comment136576750_77469166).

But that's out of the scope of this repo. Thanks for your assistance anyway :)

**Comment by jeromew** [comment]
Indeed the login/password management is not always simple. Note that for a simple setup you can use a temporary `.pgpass` file - cf https://www.postgresql.org/docs/current/libpq-pgpass.html
thanks for closing the issue and good luck on your endeavours
