### ISSUE TITLE
Parametrizing COPY ... TO STDOUT query

### ISSUE THREAD

**Issue by isRostCompany** [brianc/node-pg-copy-streams#157]
Hello.

First of all, thank you so much to everyone involved in developing this and node-postgres. 
Absolutely love working with these libraries.

I have this use case that I am not quite sure is possible with pg-copy-streams. 
I am generating csv dumps from a remote postgresql instance and streaming 
into csv dump works quite well, but I don't know how to properly parametrize 
`client.query( copyTo( "COPY (select * from test where id > $1) TO STDOUT DELIMITER \',\' CSV HEADER" ) )`.

The value of `$1` comes from user input and so it seemed that the best way is to 
pass it using parameters array (the same way it works with `client.query( sql, [1, 'foo', false])`,

but when I try to pass it that way: 
`client.query( copyTo( "COPY (select * from test where id > $1) TO STDOUT DELIMITER \',\' CSV HEADER" ), [123] )`

this error gets thrown:
```
{
  "errorType": "error",
  "errorMessage": "there is no parameter $1",
  "trace": [
    "error: there is no parameter $1",
    "    at Parser.parseErrorMessage (/var/task/node_modules/pg-protocol/dist/parser.js:283:98)",
    "    at Parser.handlePacket (/var/task/node_modules/pg-protocol/dist/parser.js:122:29)",
    "    at Parser.parse (/var/task/node_modules/pg-protocol/dist/parser.js:35:38)",
    "    at CopyStreamQuery._pgDataHandler (/var/task/node_modules/pg-protocol/dist/index.js:11:42)",
    "    at CopyStreamQuery._detach (/var/task/node_modules/pg-copy-streams/copy-to.js:55:10)",
    "    at CopyStreamQuery._parse (/var/task/node_modules/pg-copy-streams/copy-to.js:105:16)",
    "    at CopyStreamQuery._forward (/var/task/node_modules/pg-copy-streams/copy-to.js:87:28)",
    "    at CopyStreamQuery._onReadable (/var/task/node_modules/pg-copy-streams/copy-to.js:73:10)",
    "    at TLSSocket.emit (node:events:519:28)",
    "    at emitReadable_ (node:internal/streams/readable:832:12)"
  ]
}
```

is it even possible?

**Comment by jeromew** [comment]
Hello,
thanks for the report.

postgres does not support prepared statements in COPY statements.
cf https://github.com/brianc/node-pg-copy-streams/issues/92

you can probably do it client side using `pg-format`

**Comment by isRostCompany** [comment]
Hello.
Understood, thank you so much for the reply.

I will most probably refactor my code to do some programmatic loops using 
parametrized queries from node-postgres, but thanks also for the recommendation.

Closing this ticket.
