### ISSUE TITLE
Copy Binary Data from Buffer

### ISSUE THREAD

**Issue by edwardkourbanov** [brianc/node-pg-copy-streams#158]
I'm not sure if I'm doing something wrong here or if this operation is just not supported as I did not see any examples of it. I am trying to copy mass amounts of data into a table using a buffer containing the binary data. When written to a binary file, this buffer is identical to what Postgres outputs when reading to STDOUT.

I've tried writing the buffer to the ingest stream as well as piping the data but nothing seems to work and I'm not sure why.

```
const ingestStream = this.pgClient.query(
   copyFrom(
      "COPY table (device_id, timestamp, x, y, z, latitude, longitude, altitude, temperature, humidity) FROM STDIN BINARY"
   )
);
const bufferStream = Readable.from(buffer);
await pipeline(bufferStream, fileStream);
```

## Here is how I saved the buffer to a file to compare it to what Postgres outputs:
```
const fromStream = this.pgClient.query(
   copyTo(
      'COPY (SELECT device_id, timestamp, x, y, z, latitude, longitude, altitude, temperature, humidity FROM table) TO STDOUT BINARY'
   )
)
const fileStream = fs.createWriteStream(path.join(__dirname, 'binary.bin'), 'binary');
await pipeline(fromStream, fileStream);
```

## Here is how I saved the buffer to a file:
```
fs.writeFile(path.join(__dirname, 'buffer_binary.bin'), buffer, "binary", ()=>{});
```

## Here is how I created the buffer:
```
const parts = [];
//Signature
parts.push(Buffer.from([0x50, 0x47, 0x43, 0x4f, 0x50, 0x59, 0x0a, 0xff, 0x0d, 0x0a, 0x00]));

//Header empty 8 bytes
//32 bit flag fields, 32 bit extension area
parts.push(Buffer.from('0000000000000000', 'hex'));

//Tuples
parts.push(Buffer.from('000a', 'hex')) //Number of columns

//Data length
let tempBuffer = Buffer.allocUnsafe(4);
tempBuffer.writeInt32BE("860517049372172".length);
parts.push(tempBuffer); 
parts.push(Buffer.from("860517049372172")); //Data

parts.push(Buffer.from('00000008', 'hex')); //Data length
tempBuffer = Buffer.allocUnsafe(8);
tempBuffer.writeBigInt64BE(BigInt(780001471000000));
parts.push(tempBuffer); //Data timestamp

parts.push(Buffer.from('00000004', 'hex')) //Data length float
parts.push(Buffer.from(getFloatHexValue(-2), 'hex')) //Data x

parts.push(Buffer.from('00000004', 'hex')) //Data length float
parts.push(Buffer.from(getFloatHexValue(-2), 'hex')) //Data y

parts.push(Buffer.from('00000004', 'hex')) //Data length float
parts.push(Buffer.from(getFloatHexValue(3), 'hex')) //Data z

parts.push(Buffer.from('00000004', 'hex')) //Data length float
tempBuffer = Buffer.allocUnsafe(4);
tempBuffer.writeFloatBE(42.619076);
parts.push(tempBuffer) //Data lat

parts.push(Buffer.from('00000004', 'hex')) //Data length float
tempBuffer = Buffer.allocUnsafe(4);
tempBuffer.writeFloatBE(-113.67724);
parts.push(tempBuffer) //Data long

parts.push(Buffer.from('00000004', 'hex')) //Data length float
tempBuffer = Buffer.allocUnsafe(4);
tempBuffer.writeFloatBE(1);
parts.push(tempBuffer) //Data alt

parts.push(Buffer.from('00000004', 'hex')) //Data length float
tempBuffer = Buffer.allocUnsafe(4);
tempBuffer.writeFloatBE(70);
parts.push(tempBuffer) //Data temp

parts.push(Buffer.from('00000004', 'hex')) //Data length float
tempBuffer = Buffer.allocUnsafe(4);
tempBuffer.writeFloatBE(40);
parts.push(tempBuffer) //Data humidity

//File Trailer
//2 bytes containing -1
parts.push(Buffer.from('FFFF', 'hex'));


const buffer = Buffer.concat(parts);
```

Any thoughts or advice? Thank you in advance.

**Comment by jeromew** [comment]
Hello,

Thanks for the report.
I believe it should work.

Here are some questions:
- do you observe any error when you try ingesting the bufferStream ?
- did you try to ingest the binary.bin via a createReadStream and how did it go ?
- in your first snippet you have `await pipeline(bufferStream, fileStream);` it may be a copy/paste error, but you probably should have `await pipeline(bufferStream, ingestStream);` otherwise you are not testing what you think you are testing
- what is the schema of your table ?
 
For now I don't remember exactly how the binary format is built. You may want to look at what https://github.com/jeromew/node-pg-copy-streams-binary to see how it is done there.
I am not saying you should use this module as it does some heavy lifting decoding and re-encoding every field and I did not do performance test.

You are probably better off using raw `pg-node-copy-stream` like you are trying to do but it might help you understand your issue.

Keep me posted !

**Comment by edwardkourbanov** [comment]
Thanks for the response.

I got it working now although I'm not sure what I am doing different than before. I believe the culprit was ending the ingest stream by calling `ingestStream.end();`.

To answer your questions though:
1. The first time I tried ingesting the stream it would just hangup almost as if it was stuck in an infinite loop. No errors or anything. My debugger just stopped.
2. I believe I tried this as well to no avail. I'm sure I was missing something though and it is possible.
3. That was a typo. My bad. I was calling `await pipeline(bufferStream, ingestStream);`.
4. The table contains id (primary key), date_created (timestamptz default now()), date_updated (timestamptz), device_id (varchar(255)),  timestamp (timestamptz), x (integer), y (integer), z (integer), latitude (real), longitude (real), altitude(real), temperature (real), humidity (real). In my query I am only inserting a subset of that as can be seen in the COPY statement.


Here is how my code is structured now that it's working:
```
const buffer = Buffer.concat(parts);

const bufferStream = Readable.from(buffer);
await pipeline(bufferStream, ingestStream);

ingestStream.end();

```

**Comment by jeromew** [comment]
ok great.
it is always better when possible to copy/paste full snippets.
I believe `pipeline` takes care of calling `end()` so the behavior you describe when calling `ingestStream.end();` seems a bit undefined.

does it stop working if you do not add the `ingestStream.end();` line ?

**Comment by jeromew** [comment]
Feel free to re-open if you want to dig further
