### ISSUE TITLE
Permissions to run this on the DB

### ISSUE THREAD

**Issue by iamlothian** [brianc/node-pg-copy-streams#18]
From the look of things this module is just wrapping the native [COPY](http://www.postgresql.org/docs/9.3/static/sql-copy.html) into a stream right? and has nothing to do with the psql (cli) [\copy](http://www.postgresql.org/docs/9.3/static/app-psql.html#APP-PSQL-META-COMMANDS-COPY)

I ask because, native COPY requires superuser privileges to run where the cli version does not.

If i need the \copy version am i better off finding some cli interface for node?

**Comment by jeromew** [comment]
issue seem to have been resolved. closing.
