### ISSUE TITLE
Invalid byte sequence error

### ISSUE THREAD

**Issue by ilyabo** [brianc/node-pg-copy-streams#22]
I am getting this error while trying to import a CSV file with about 400k lines into Postgres:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
error: invalid byte sequence for encoding "UTF8": 0x00
    at Connection.parseE (/Users/ilyabo/Workspace/edge/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/ilyabo/Workspace/edge/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/ilyabo/Workspace/edge/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
```

I use the following code for import: 

```
  var stream = client.query(pgCopy.from(
    "COPY "+table.name+" FROM STDIN WITH CSV HEADER DELIMITER ','"
  ));

  var fileStream = fs.createReadStream(INPUT_DIR + '/' + table.name + '.csv')
  fileStream.on('error', done);
  fileStream.pipe(stream)
    .on('finish', done)
    .on('error', done);
```

The CSV file itself seems fine. It doesn't appear to have non-ascii characters in it. Importing it directly by specifying the full path in the Postgres query works just fine:

```
COPY edge_counts FROM '/Users/ilyabo/Workspace/edge.csv' WITH CSV HEADER DELIMITER ',';
```

Moreover, when I reduce the number of rows in the file to something like 50k (doesn't seem to matter which 50k lines!), the import via pg-copy works too.

What could be the cause of this error?

**Comment by brianc** [comment]
That is really odd. My only hunch is you might want to specify the type of encoding from the file you're reading?

```js
createReadStream(fileName, { encoding: 'utf8' })
```

Other than that...can you supply a way for me to test this locally? Some self-contained test case that demonstrates the behavior?

**Comment by ilyabo** [comment]
Thanks for the quick response!  `{ encoding: 'utf8' }` doesn't help. Although, I noticed that it works when importing to another Postgres running on a different machine. Can I send you the test case by email?

**Comment by brianc** [comment]
shure thang!

**Comment by ilyabo** [comment]
Hm, I cannot reproduce it in a test case reliably. It seems to have to do with the fact that I am reusing the same pg client for multiple queries. Could it be the reason?

**Comment by ilyabo** [comment]
This is roughly what I am doing, trying to run a few tasks synchronously:
```
var queue = require('queue-async');
pg.connect(dbUrl, function(err, client, done) {
  if (err) return handleError(err, client, done);

  var q = queue(1);
  TABLES
    .forEach(function(table) {
      q.defer(dropTable, client, table);
      q.defer(createTable, client, table);
      q.defer(importTable, client, table);
    });

  q.await(function(err) {
    done();

    if (err) return handleError(err, client, done);
    console.log('done');
    client.end();   
  });

});



function importTable(client, table, done) {
  var stream = client.query(pgCopy.from(
    "COPY "+table.name+" FROM STDIN WITH CSV HEADER DELIMITER ','"
  ));

  var fileStream = fs.createReadStream(
    INPUT_DIR + '/' + table.name + '.csv',
    { encoding: 'utf8' }
  );
  fileStream.on('error', done);
  fileStream.pipe(stream)
    .on('finish', done)
    .on('error', done);
}
```

And it seems that client.end() sometimes gets called too early for some reason, resulting in `error: unexpected message type 0x58 during COPY from stdin`. 

If I defer client.end like this: `setTimeout(function() { client.end(); }, 1000);` then the error doesn't appear. But it's all weird. Is there some buffer to flush?

**Comment by aaronlidman** [comment]
I'm also hitting both errors described in this last comment consistently. Especially weird is `finish` being emitted early.

**Comment by ebiven** [comment]
The authors discuss this some in PR#15: https://github.com/brianc/node-pg-copy-streams/pull/15

Essentially `finish` is firing immediately after the final call to `_transform` but is happening before the `_flush`. This library sends finalization data on `_flush`, so in cases where your app closes the streams before `_flush` can run you're going to usually get 0x58:

http://www.postgresql.org/message-id/23491.1282762906@sss.pgh.pa.us

Simply using the `end` event will get you around this problem.

It can probably be argued that the Node docs are wrong, but the code is pretty clear:

https://github.com/joyent/node/blob/1da7bcc22ca115d4cb17193bc97cda027ebe2e30/lib/_stream_transform.js#L128-L136

**Comment by jeromew** [comment]
Can you try with version 1.2.0 ?

Listening to the 'end' event is currently the correct way to wait for the completion of the command (I just added a bit of doc in README on this)

version 1.2.0 fixed some chunk boundary issues which you may have encountered on a big file that could maybe explain the unexpected 0x00 byte.

**Comment by dhautotlf** [comment]
I had the same issue but realised I was listening on the `end` event of the `fileStream` instead of the `queryStream`. 
I couldn't reproduce in dev env since files were pretty small. When trying in prod I had the `unexpected message type 0x58 during COPY from stdin` since I was trying to end the pg connection before the end of the streaming.

**Comment by jeromew** [comment]
@dhautotlf thanks for the feedback. Do you mean that you still have an error after listening for 'end' on `stream` ?

**Comment by dhautotlf** [comment]
@jeromew No I don't anymore. I am on v1.2.0

**Comment by jeromew** [comment]
@dhautotlf ok thanks. I'll leave this issue open a bit more to see if @ilyabo has any feedback.

**Comment by arsinawaz** [comment]
i am also facing the same issue, does it have something to do with the CSV file encoding? because it works fine with UTF-8 but not with ANSI..

**Comment by jeromew** [comment]
@arsinawaz thanks for the feedback. do you by any chance have a self-contained example that demonstrates the failure ?

I haven't tested myself with encoding discrepancies. When nodes reads the file, I suppose that it should be read with the same encoding as the pg client uses.

There is an ENCODING section on https://www.postgresql.org/docs/9.6/static/sql-copy.html but it only deals with the encoding that should be used to open a file. It is probably not applicable when streaming from stdin.

**Comment by arsinawaz** [comment]
@jeromew in my case i solved it by detecting the encoding of the file and providing it to the copy command as below:

```
var fileBuffer = fs.readFileSync(req.files.file.path);
var enc = charset(fileBuffer);
enc = enc || jschardet.detect(fileBuffer).encoding.toLowerCase();

var sql = "COPY tablename FROM STDIN  encoding '" + enc + "'";
var stream = client.query(copyFrom(sql));
var fileStream = fs.createReadStream(__dirname + '/' + req.files.file.path)

fileStream.pipe(stream);
stream.on('end', function(result){
      console.log('done!');
});
```

**Comment by jeromew** [comment]
OK thanks. That would make sense. You read the file byte-by-byte as (without specifying an encoding at the node.js level). And then you instruct "COPY FROM" that the byte sequence will come in the detected encoding (as long as postgres knows how to deal with the encoding).

I believe this should also work if the pg client is created with the target encoding (since 'COPY FROM' would fallback to this encoding by default according to doc.) So it seems that the 'encoding' parameter is also used the source file is "stdin".
