### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by jwhitehorn** [brianc/node-pg-copy-streams#23]
It doesn't appear that this module is on NPM. Is that intentional? Am I just overlooking it?

It's not that huge of an issue, but it was a little unexpected.

**Comment by brianc** [comment]
This works for me:
https://github.com/brianc/node-pg-copy-streams#install

**Comment by brianc** [comment]
what problem are you running into?

**Comment by jwhitehorn** [comment]
My bad, I was in a hurry and assumed the module's name matched the repo name. I should really RTFM, :smile:
