### ISSUE TITLE
Does not work with pg > 3.0.0

### ISSUE THREAD

**Issue by cpapazian** [brianc/node-pg-copy-streams#25]
I am getting errors when using this library with versions of node-postgres (pg) greater than 3. It looks like the activeQuery is not getting cleaned up when the copy query finishes, causing a connection error when the pg connection is closed (via client.end() or pg.end()).

**Comment by shaunc** [comment]
Could this also be related to https://github.com/brianc/node-pg-copy-streams/pull/28/files ? (some messages from the server aren't consumed because of unshift behavior). I thought that was also possibly related to node >= 0.12.

**Comment by cpapazian** [comment]
It is related! Everything works with node 0.10 and with node 0.12 and your fix applied. :+1:

**Comment by jeromew** [comment]
I am closing this issue for now. please re-open if you still have problems with 1.2.0
