### ISSUE TITLE
documentation note?

### ISSUE THREAD

**Issue by shaunc** [brianc/node-pg-copy-streams#26]
It would seem from the postgres doc that wrapping in transaction might not be sufficient (or necessary?) to undo the effect of an error in copyFrom:

>  COPY stops operation at the first error. This should not lead to problems in the event of a COPY TO,  but the target table will already have received earlier rows in a COPY FROM. These rows will not be visible or accessible, but they still occupy disk space. This might amount to a considerable amount of wasted disk space if the failure happened well into a large copy operation. You might wish to invoke VACUUM to recover the wasted space.

Perhaps this would be good to note in the documentation (right around the "half-borked" part :))?

**Comment by jeromew** [comment]
Right. For further reference, the text is extracted from https://www.postgresql.org/docs/current/static/sql-copy.html

**Comment by jeromew** [comment]
I added the mention in the README + asked the question on pg-general to know if relying on auto-vacuum is sufficient here. Will update the doc if something comes out of it.
