### ISSUE TITLE
flush() support?

### ISSUE THREAD

**Issue by aberenyi** [brianc/node-pg-copy-streams#30]
Hi,

We have a data feed that sends 6-10 data packages per sec. I wanted to leverage the power of `COPY` to insert the (preprocessed) data into the database. Unfortunately failed so far.

What I'd like to achieve is to set up some sort of limit (let's say 1000 `row` event or data package) and when the limit is reached the stream would fire the query to the DB and clean up itself.

I've tried to use `stream.end()` and then recreate `stream`, but it does not really work and it is far from being an elegant solution.

Is there any way to flush the stream? I've found the `_flush()` private method, but that is not for this purpose I guess.

Cheers

**Comment by aberenyi** [comment]
Can I use `submit(connection)` for this?

**Comment by aberenyi** [comment]
[This](https://gist.github.com/aberenyi/12dc416e99737d660f09) works, however, not too elegant...

**Comment by jeromew** [comment]
At this stage, there is no plan to integrate a batch mode inside this module. I can understand the use case but there is no way to to interim commits on a COPY so the only solution I can think of is the one you mentioned in your example : several calls to COPY.
