### ISSUE TITLE
Connection Terminated - Node 4.2.2

### ISSUE THREAD

**Issue by chriskinsman** [brianc/node-pg-copy-streams#34]
Connecting to Postgres 9.3 / AWS RDS
Running under node 4.2.2

Recently switched from an old version of PG with built in copy streams to pg 4.4.3 and node-pg-copy-streams 0.3.0

After a while export is terminating with:

stream error exporting data [Error: Connection terminated]

Tried merging: https://github.com/brianc/node-pg-copy-streams/pull/28 to see if it helped but no go.

Any thoughts?

**Comment by chriskinsman** [comment]
Made a change.  I was piping to s3-stream-upload before.  Changed to a filestream() and it worked just fine.  s3-stream-upload is going to be slower than the filestream so it is going to create upstream back pressure that the filestream may not

**Comment by chriskinsman** [comment]
Determined to be issue with s3-stream-upload not emitting a drain event properly

**Comment by chriskinsman** [comment]
Confirmed that https://github.com/brianc/node-pg-copy-streams/pull/28/files fixes my issue.  Would be nice to merge this pull request...

**Comment by chriskinsman** [comment]
Actually this got me further but still occasionally seeing connection terminated.  Working on repro case...

**Comment by chriskinsman** [comment]
After a bit more work it appears that what is happening is related to connection pooling.  If I remove the connection pooling and switch to just connecting with the client the issue disappears.  

I applied  https://github.com/brianc/node-pg-copy-streams/pull/28 but it feels like there is still something  missing.

**Comment by chriskinsman** [comment]
It is looking like the client.activeQuery isn't cleared by the time end() is called which causes the connection terminated event to be raised.

I am calling .end() on the client when I receive finish from the destination stream.

**Comment by chriskinsman** [comment]
It looks like client.activeQuery isn't cleared because the commandComplete and/or readyForQuery was being lost from connection.stream when the stream I was piped into unpaused the connection.  

unpiping the stream prior to pausing it helped with this it appears and I more reliable see node-postgres pick up the commandComplete and readyForQuery messages.

Still hitting issues however with a TCP._onclose() firing occasionally that sends a end event to the node-postgres client before the activeQuery is closed causing an error to be thrown

**Comment by cbaron** [comment]
I think I'm seeing something similar when trying to stream image data from a bytea column.  One or two streams are properly opened, read from, and closed, but then the next stream seems to never get data written to it.  Anyone want to help me work through this?  I would be happy to do some work with a goal of a pull request in return.

**Comment by jeromew** [comment]
hello. This issue starts getting old. Can you try with version 1.2.0 ? There have been some fixes to chunk boundary detection that could explain lost or late messages.

we would probably need a repro test case to go further.

**Comment by tutukin** [comment]
[output.txt](https://github.com/brianc/node-pg-copy-streams/files/1306757/output.txt)
I have a similar problem with activeQuery not cleaned after copyFrom finishes Below is the code. The output is attached.

Ubuntu 16.04 LTS
nodejs 8.2.1
postgresql 9.5
pg 7.1.0
pg-copy-streams 1.2.0

```javascript
const streamEvents = 'close data drain end error finish readable pipe';
const copyFrom = require('pg-copy-streams').from;
const { Client } = require('pg');

const connectionString = 'postgresql://user:passuser@localhost:5432/proto-pgs';
const sqlCopy = `COPY command(type,message,id) FROM STDIN DELIMITER '|'`;
const sqlInsert = `INSERT INTO command(type,message,id) VALUES($1,$2,$3)`;
work();

async function work() {
    const client = new Client({ connectionString });
    await client.connect();
    logEvents(client, 'Conn', streamEvents);

    const res = await client.query(sqlInsert, ['insert', 'insert msg', `msg-${Date.now()}`]);
    console.dir(res);

    const stream = client.query(copyFrom(sqlCopy));
    stream.on('finish', async () => await client.end());
    logEvents(stream, 'CS', streamEvents);

    for (let i = 0; i < 3; i++) {
        const row = `copy|message #${i}|msg-${i + Date.now()}\n`;
        stream.write(Buffer.from(row));
    }

    stream.end();
}


function logEvents(target, name, events=[]) {
    events = Array.isArray(events) ?
        events :
        events.split(/[\s:;,]+/g);
    events.forEach(n => target.on(n, a => console.log(`Ev: ${n}(${name}): ${str(a)}`)));
}

function str(obj) {
    if (obj === undefined) {
        return 'undefined';
    }

    const isError = obj instanceof Error;
    if (isError) {
        obj = {
            message: obj.message,
            stack: obj.stack
        };
    }

    const s = JSON.stringify(obj);

    return !isError && s.length > 115 ?
        s.substr(0, 114) + '…' :
        s;
}
```

**Comment by tutukin** [comment]
There is something wrong with logEvents, especially, logging 'data' event on the stream. When I removed logEvents entirely, added listeners to 'error' and 'end' on both client and stream everything works fine.

**Comment by jeromew** [comment]
Hello, sorry for the delay on this. 
I suspect that when logEvents adds an `.on('data')` it triggers https://nodejs.org/api/stream.html#stream_event_data

> Attaching a 'data' event listener to a stream that has not been explicitly paused will switch the stream into flowing mode. Data will then be passed as soon as it is available.

I am not sure of the way you could fix that. maybe calling https://nodejs.org/api/stream.html#stream_readable_pause could help keep the stream in non-flowing mode.

I am closing this for now as it is and old issue. Feel free to re-open if needed.
