### ISSUE TITLE
Add @jeromew as npm package owner

### ISSUE THREAD

**Issue by brianc** [brianc/node-pg-copy-streams#55]
Hey @jeromew - if you'd like you can submit a PR with npm name added as a [package owner](https://docs.npmjs.com/cli/owner).  I can then publish to npm and after that both of us can publish!

**Comment by jeromew** [comment]
@brianc thanks ! I will do that shortly after merging the PRs

**Comment by jeromew** [comment]
@brianc I am not sure what I am supposed to do after reading the link you provided.

    npm owner add jeromew pg-copy-streams

gave me

    you do not have permission to publish "pg-copy-streams". Are you logged in as the correct user? : pg-copy-streams

**Comment by brianc** [comment]
ah i can do it - i really just needed your npm name.  Wasn't sure if it was the same as your github name. :smile:

**Comment by jeromew** [comment]
npm whoami => jeromew

**Comment by brianc** [comment]
okay I added you!

**Comment by jeromew** [comment]
thanks. It seems to have worked. I am going to try and publish a new minor version with the recent PRs.

**Comment by brianc** [comment]
awesome!  you should be able to just run `make minor` in the project dir

https://github.com/brianc/node-pg-copy-streams/blob/master/Makefile#L11

**Comment by jeromew** [comment]
Done !
