### ISSUE TITLE
getting TypeError: dest.end is not a function while trying to use a Buffer instead of a file's read stream for copy-from

### ISSUE THREAD

**Issue by chrismark** [brianc/node-pg-copy-streams#58]
Hi,

I'm getting error from attempting to use copy-from with a Buffer instead of file. Is this possible? Will I need to write my own Read/Write-er stream object?

>>TypeError: dest.end is not a function
>>    at PassThrough.onend (_stream_readable.js:498:10)
>>    at PassThrough.g (events.js:273:16)
>>    at emitNone (events.js:85:20)
>>    at PassThrough.emit (events.js:179:7)
>>    at endReadableNT (_stream_readable.js:913:12)
>>    at _combinedTickCallback (node.js:383:13)
>>    at process._tickCallback (node.js:407:11)

And here's my code (sorry can't get markdown to work):

        return pg_pool.connect(function (error, pgClient, pgDone) {

            var streamCopy = pgClient.query(copyFrom('COPY mytable FROM STDIN'));
            // Initiate the source
            console.log('creating bufferStream');
            var bufferStream = new stream.PassThrough();

            console.log('attaching error handler to bufferStream');
            bufferStream.on('error', pgDone);

            console.log('attaching error handler to streamCopy');
            streamCopy.on('error', pgDone);

            console.log('attaching end handler to bufferStream');
            streamCopy.on('end', pgDone);
            //streamCopy.on('finish', function () {
            //    console.log('finish', arguments);
            //});

            fileLogger.log('Start DB insert');
            TimeElapsed.start('db_insert');

            // Write your buffer
            console.log('writing bufferArray[index] to bufferStream');
            bufferStream.end(bufferArray[index]);

            // Pipe it to COPY
            console.log('pipe bufferStream to streamCopy');
            bufferStream.pipe(streamCopy);

        });

I'm getting some data from a feed using sockets, then formatting that data into multivalue INSERTS, accumulating, then putting inside Buffers so that I have an array of Buffer objects.  (Now that I think of it should have been individual row inserts, but I think it's not the cause of the error).

**Comment by jeromew** [comment]
Sorry for the delay on this. it is ok to pipe data direcly into the copyFrom. Cf tests in test/copy-from.js for examples. Feel free to reopen if needed.
