### ISSUE TITLE
Database instead of table

### ISSUE THREAD

**Issue by davidgatti** [brianc/node-pg-copy-streams#60]
Hi @brianc, 

I have a project where I'm downloading a database backup as a stream and then pipe it to decrypt it, and then pipe to a file. I would love to skip the file step and stream the decrypted SQL directly in to the database.

The backup is created using pg_dump so I have the whole DB structure. In your example you have the following line:
```
var stream = client.query(copyFrom('COPY my_table FROM STDIN'));
```

If you have a moment could you explain what this `COPY my_table FROM STDIN` means? Dose it mean that I have to have the whole DB structure and can only import the data?

Or could I some how have an empty DB, and not only import the data but also the whole structure?

**Comment by jeromew** [comment]
Hello sorry for the delay on this.
If still needed, check the "COPY" documentation https://www.postgresql.org/docs/9.3/sql-copy.html
COPY is a very specific construct to stream from and to 1 table. The table need to be pre-existing.
if you look into a text dump of pg_dump with the correct options, you will see commands that create the structures of the tables + COPY commands that copy the data.
but this module cannot be used to dump/restore a full DB nor create the structure of the tables.
I hope this answers your question.
