### ISSUE TITLE
CopyTo: `end` event does not guarantee stream is flushed

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [brianc/node-pg-copy-streams#61]
I have the following code, testing the file size when copying from table to file:

```js
var pg = require('pg');
var pgTo = require('pg-copy-streams').to;
var fs = require('fs');

   var client = new pg.Client(connString);
    client.connect(function (err) {

        var _cb = function(what) {
            console.log(what, 'file size:', fs.statSync(outFile).size);
        };

        var tmpStream = fs.createWriteStream(outFile);
        tmpStream.on('end', function () {
            _cb("tmpStream.on('end')");
        });

        tmpStream.on('finish', function () {
            _cb("tmpStream.on('finish')");
        });
        
        var srcStream = client.query(pgTo(sql));
        srcStream.on('error', function (err) {
            _cb("srcStream.on('error')");
        });
        srcStream.on('end', function () {
            _cb("srcStream.on('end')");

            //this is only to check the file size a bit later, too
            process.nextTick(function () {
                _cb("srcStream.on('end') second call");
            });
        });

        srcStream.pipe(tmpStream);
    });
```

My problem is that at the moment when `srcStream.on('end')` is called (recommended for use, rather than `tmpStream.on('finish')`, the file is not always ready yet. Actually only at `tmpStream.on('finish')` it is ready. Sample output:

```bash
srcStream.on('end') file size: 755020
srcStream.on('end') second call file size: 755020
#the correct file size:
tmpStream.on('finish') file size: 762760 
```
Another example (exporting different table) is even worse, because the file size is 0:

```bash
srcStream.on('end') file size: 0
srcStream.on('end') second call file size: 0
tmpStream.on('finish') file size: 10889
```

**Comment by jeromew** [comment]
Hello. Thanks for using this lib !

I think you make reference to the block

> Important: Even if pg-copy-streams.from is used as a Writable (via pipe), you should not listen for the 'finish' event and expect that the COPY command has already been correctly acknowledged by the database. Internally, a duplex stream is used to pipe the data into the database connection and the COPY command should be considered complete only when the 'end' event is triggered.

this warning is in reference to `require('pg-copy-streams').from` when you are saving something to the database.

in your case, writing from the database to a file (your `tmpStream`) you are totally correct that only the 'finish' event will tell you when the file has been written to the disk.

**Comment by ktrzeciaknubisa** [comment]
Oh, in that case let's at least make a note in relevant a sample in README :)

Thanks :)
