### ISSUE TITLE
Question: how to handle constraints?

### ISSUE THREAD

**Issue by robertpallas** [brianc/node-pg-copy-streams#62]
My db has foreign key constraints. I am using csv export format. Problem is that table A has reference to table B and it is alphabetically before B thus import is failing. Is there eloquent workarounds? Other options to use? I am using export and import a lot so manually adding numbers to overcome alphabetic order is not an option.

**Comment by jeromew** [comment]
Hello,

I must admit I don't totally understand how this is is related to `pg-copy-streams`.
the `COPY` command works on one table so any reference constraint has to be handled externally and that would be also true if you were using COPY via psql.

one way to do it that may or may not be ok in your use case is to remove the foreign key constraints before import and rebuild them after.

**Comment by robertpallas** [comment]
Thanks @jeromew , helpful idea.
