### ISSUE TITLE
can we use querystream (multiple  insert statement)

### ISSUE THREAD

**Issue by matt212** [brianc/node-pg-copy-streams#64]
Hi, 
below is provided sample code for pg copy streams

```
var fs = require('fs');
var pg = require('pg');
var copyFrom = require('pg-copy-streams').from;

pg.connect(function(err, client, done) {
  var stream = client.query(copyFrom('COPY my_table FROM STDIN'));
  var fileStream = fs.createReadStream('some_file.tsv')
  fileStream.on('error', done);
  stream.on('error', done);
  stream.on('end', done);
  fileStream.pipe(stream);
});
```

my query is can we stream multiple insert statements rather than tsv file . since we can create querystream 

something like below codebase 
```
  pg.connect(connectionString,function(err, client, done) {
  if(err) 
    {
        console.log(err)
    }

  
var basescrp=format('INSERT INTO srt (starttime, endtime,content,showname,season,ep,createdat,updatedat) VALUES %L', data)

 
  var stream = client.query(copyFrom('COPY srt FROM STDIN'));
  
  //release the client when the stream is finished
  var rs = new QueryStream(basescrp)
  
rs.pipe(stream).on('finish', done).on('error', function (err) {
    console.log(err);
    done();
  });

})
```
 since above code does not work actually !
any pointer on how to stream bulkinsert into postgres

**Comment by matt212** [comment]
I seems to stumbled upon an old repo of yours for [writable stream](node-pg-writable) , which is what i was somewhat looking for but there is some auth issue with it  .
[pg.js auth issue persist](https://github.com/brianc/node-pg-writable/issues/1) .
Could you please guide me in solving that issue !
Many thanks !

**Comment by matt212** [comment]
Ok , 
I got a hold of writable stream  and expanded on approach using through2 ,
there are some new issues , but the got the momentum required to achieve the objective  and closing this case scenario. 
Thanks !

**Comment by jeromew** [comment]
Hello.
Even if this is closed, I do not quite understand your use case.
From what I understand, you could have used the COPY command like so, without resorting to QueryStream.

    var stream = client.query(copyFrom('COPY srt (starttime, endtime,content,showname,season,ep,createdat,updatedat) FROM STDIN'));

If the tsv file has the correct columns, this will work.

**Comment by matt212** [comment]
Hi, 
@jeromew  , 
1.I don't have tsv file and also progress is below code which should work but is not working due to 
 what my assumption is delimiter issue even for single column insert
https://github.com/brianc/node-pg-copy-streams/issues/65
```
var stream = client.query(copyFrom('COPY srt(starttime) FROM STDIN '));

console.log(data)


var internmap = through2.obj(function(arr, enc, cb) {
   var rowText = arr.join('\t') + '\n'
console.log(rowText);
   cb(null, rowText)
 })
internmap.write(data);

internmap.pipe(stream)

```
any pointers , suggestions

**Comment by jeromew** [comment]
@matt212 no, I think your problem comes from the trailing '\n'. Each newline instructs postgres to wait for a new row so you only need them in-between rows (not before the first and not after the last)
