### ISSUE TITLE
Delimiters specs 

### ISSUE THREAD

**Issue by matt212** [brianc/node-pg-copy-streams#65]
Hi, 
using node -v [8.1.4]
below is my codebase
 ```

var stream = client.query(copyFrom('COPY srt(starttime) FROM STDIN '));

console.log(data)


var internmap = through2.obj(function(arr, enc, cb) {
    var rowText = arr.join('\t') + '\n'
console.log(rowText);
    cb(null, rowText)
  })
internmap.write(data);

internmap.pipe(stream)


``` 

the issue which i am facing is below 
![copyto](https://user-images.githubusercontent.com/1698139/28757052-d49366c6-752f-11e7-9828-db0896c86189.png)

even tried putting tabs on 
with below codebase 
![both](https://user-images.githubusercontent.com/1698139/28757213-8604dce4-7532-11e7-891a-2998cc97e70e.png)

the issues seems to with delimiter specs
any pointer on where should i define.
 Ideally \t tabs is by default applied , but in my case it is not working.
Any pointers , suggestions on how to resolve this !

**Comment by jeromew** [comment]
Check https://www.postgresql.org/docs/9.2/static/sql-copy.html for documentation of the COPY command. Default delimiter is tab so you should be ok.

you problem probably comes from the fact that the last line should not terminate with a newline (otherwise, postgres thinks you want to add one more row, and is lost)

**Comment by matt212** [comment]
Hi @jeronew, 
thanks for heads up i was referring to old writable repo.
https://github.com/brianc/node-pg-writable/blob/master/index.js
i am quiet nascent in terms of modifying stream and also Copy command
Also  even if i remove \n from below codebase:-
`  var rowText = arr.join('\t') + '\n'`
to 
`  var rowText = arr.join('\t')`
the chunks from  on data callback    is below and it is not getting inserted into database 
![copy issues](https://user-images.githubusercontent.com/1698139/28768431-2e3b9f3e-75f5-11e7-93a1-aa4729154613.png)

**Comment by jeromew** [comment]
you need the '\n' between each rows.

**Comment by matt212** [comment]
hi @jeromew ,
extremely sorry missed your post content  with for newline '\n'
also even after appending newline first 
`var rowText = '\n' + arr.join('\t')`
 nothing is happening
I think there is some issue  with my below code 

```
internmap.write(data);
internmap.pipe(stream);

```
or data 
![data](https://user-images.githubusercontent.com/1698139/28769269-67c6929c-75f8-11e7-9ced-0c7324babcd8.png)
any pointers 
thanks for patience !

**Comment by jeromew** [comment]
should be something like

    var started = false;
    var internmap = through2.obj(function(arr, enc, cb) {
       var rowText = (started ? '\n' : '') + arr.join('\t');
       started = true;
       cb(null, rowText);
    })

+ maybe remove 
    internmap.on('data', function(chunk) {
      console.log(chunk);
   })

because this sometimes is greedy and consumes data before the stream pipeline is operational (cf documentation on flowing vs non-flowing streams)

**Comment by matt212** [comment]
Hi @jeromew 
thank you so much i forgot to flush after write !
however , when i do that, I get below error
![geez](https://user-images.githubusercontent.com/1698139/28772344-8fa340ca-7603-11e7-8149-2974d1bf1440.png)

updated code snippet with sample dataset
```
var sqlcopysyntax = 'COPY intern(starttime) FROM STDIN ';

            var stream = client.query(copyFrom(sqlcopysyntax));

            console.log(sqlcopysyntax)


            var interndataset = [
                ['0.382'],
                ['5.918'],
                ['19.554'],
                ['24.151'],
                ['25.507'],
                ['27.734'],
                ['27.734'],
                ['29.336'],
                ['31.71'],
            ];

            var started = false;
            var internmap = through2.obj(function(arr, enc, cb) {
                var rowText = (started ? '\n' : '') + arr.join('\t');
                started = true;
                //console.log(rowText)
                cb(null, rowText);
            })

            internmap.write(interndataset);
            internmap.end();

            internmap.pipe(stream);


            internmap.on('data', function(chunk) {
                console.log(chunk);
            })

            stream.on('finish', function() {
                resolve(0);


            })
            stream.on('error', function(err) {
                console.log(err)
                resolve(0);

            })


            internmap.on('finish', function() {
                resolve(0);


            })


            internmap.on('error', function(err) {
                console.log(err)
                resolve(0);
            })
```
my postgres table ddl

```
CREATE TABLE public.intern (
	starttime varchar NULL
)
WITH (
	OIDS=FALSE
) ;
```
i think i might have some issues with array interndataset  , since now it is single column moving forward it would multiple columns with ofcouse copy statement to two columns 
 var interndataset = [
                ['0.382','5.918'],
                ['5.918','5.918'],
                ['19.554','5.918'],
                ['24.151','5.918'],
                ['25.507','5.918'],
                ['27.734','5.918'],
                ['27.734','5.918'],
                ['29.336','5.918'],
                ['31.71','5.918'],
            ]; 

any pointers

**Comment by matt212** [comment]
Hi @jeromew , 
got it working for single column entry ,now stuck up with multiple column entry

necessary modification in code snippets!

from 
` var rowText = (started ? '\n' : '') + arr.join('\t');`
to this
`  var rowText = '\n'  + arr.map( function( item ){ return ('\n' +item.join('\t'))  } ).join('');`

this works for single column inserts, but working on multi column insert  like for 
e.g -
```
var interndataset = [
                ['0.382','5.918'],
                ['5.918','5.918'],
                ['19.554','5.918'],
                ['24.151','5.918'],
                ['25.507','5.918'],
                ['27.734','5.918'],
                ['27.734','5.918'],
                ['29.336','5.918'],
                ['31.71','5.918'],
            ]; 
```
any pointers on how to modify for more than one columns ?
Thanks for your understanding and patience !

**Comment by jeromew** [comment]
I think there is a mismatch of things in your approach.
you should enter 'through2.obj' with row level data.


            var started = false;
            var internmap = through2.obj(function(arr, enc, cb) {
                var rowText = (started ? '\n' : '') + arr.join('\t');
                started = true;
                //console.log(rowText)
                cb(null, rowText);
            })

            interndataset.forEach(function(r) {
              internmap.write(r);
            })
            internmap.end();

then make sure your table has 2 columns.

**Comment by matt212** [comment]
hi @jeromew , 
you sir are lifesaver !
