### ISSUE TITLE
Are query parameters supported?

### ISSUE THREAD

**Issue by chriszrc** [brianc/node-pg-copy-streams#67]
Copy supports queries, not just tables:

`COPY { table_name [ ( column [, ...] ) ] | ( query ) }`

Is it possible to send parameters to the query included in the copyTo command? Our use case here is that we are creating an csv export service, and with this library, we can export csv data directly from postgres to s3

**Comment by furstenheim** [comment]
According to this issue https://github.com/brianc/node-postgres/issues/920 it is not supported by the copy statement itself

**Comment by chriszrc** [comment]
The snippet from above is taken right from the postgres docs:

```sql
COPY { table_name [ ( column_name [, ...] ) ] | ( query ) }
    TO { 'filename' | PROGRAM 'command' | STDOUT }
    [ [ WITH ] ( option [, ...] ) ]
```

https://www.postgresql.org/docs/current/static/sql-copy.html
