### ISSUE TITLE
Cannot execute on אable names with uppercase letter 

### ISSUE THREAD

**Issue by aviranco** [brianc/node-pg-copy-streams#78]
Hi,

When I am trying to copy table content when the table name has upper case it fails, saying that the table not exist (with the lower cased name of the table).

e.g. when trying to execute the following: s`COPY my_schema.Entity TO STDOUT`
I get error: `error: relation "my_schema.entity" does not exist`

**After renaming the table name to lower case it works**

**Comment by jeromew** [comment]
Hello. Thanks for the report. I don't really see where `pg-copy-streams` would have an impact on this. it simply forwards the sql COPY command to postgres. do have a test case that we could add to the test suite showing what goes wrong ?

**Comment by jeromew** [comment]
Also please check https://stackoverflow.com/questions/43111996/why-postgresql-does-not-like-uppercase-table-names that might be related.

**Comment by jeromew** [comment]
I'll close this issue now I don't think this is related to the `pg-copy-streams` module. Feel free to re-open with a test case.
