### ISSUE TITLE
Does not work with table names that contain upper cases, only _

### ISSUE THREAD

**Issue by aviranco** [brianc/node-pg-copy-streams#80]
As title describes, there are errors when using tables and relations to tables that contain upper cases.

**Comment by jeromew** [comment]
I don't think this is a problem with `pg-copy-streams`. It is considered bad practice to use upper cases in table names in postgres. cf https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_upper_case_table_or_column_names
