### ISSUE TITLE
Synchronous or Promises management

### ISSUE THREAD

**Issue by H3r3zy** [brianc/node-pg-copy-streams#83]
Hello,

I work with Google Function and Google don't like when there is background task.
I try to make a Promise resolved in the end event of filestream but there is nothing to do, it's don't work.

here is an exemple of what I made:
```
const promise = new Promise((resolve, reject) => {
            pool.connect((err, client, done) => {
                let fsStream = client.query(copyFrom('COPY table (some data) FROM STDIN WITH (FORMAT CSV, DELIMITER \';\')'));

                fsStream.on('end', () => {
                    pool.end();
                    res.set({
                        "Access-Control-Allow-Origin": "*",
                        "Access-Control-Allow-Credentials": "true",
                    });
                    res.status(200).send('OK');
                    resolve('OK');
                });
                fsStream.on('error', (e) => {
                    console.log('error', e);
                    process.stdout.write(' KO\n');
                    pool.end();
                    reject(e);
                });

               
                for (const data of datas) {
                    csv += 'some data';

                    if (csv.length > 30878915) {
                        fsStream.write(csv);
                        csv= '';
                    }
                }
               
                fsStream.write(csv);
                fsStream.end(null);
            });
        });
        return promise;
```

there is a way to do copyFrom with promise or something synchronous ?

**Comment by gajus** [comment]
Not equivalent functionality to what you are asking, but Slonik [`copyFromBinary`](https://github.com/gajus/slonik#copyfrombinary) uses Promises.

There is no interface for CSV though or `COPY TO` at the moment, though.

**Comment by jeromew** [comment]
I don't see a reason why you could wrap the library inside a promise but it is hard to debug your specific code. Maybe try to write a self-contained test that people can try (you can check inside the test directory there are many tests). At this stage i will close the issue but do not hesitate to re-open.
