### ISSUE TITLE
EventEmitter memory leak upon error

### ISSUE THREAD

**Issue by adam-nielsen** [brianc/node-pg-copy-streams#85]
If you run multiple copy streams one after the other (e.g. to cope with errors in the data and to retry with smaller chunks until the offending rows can be discarded) then you quickly end up with a lot of these errors:
```
pg-copy-streams/index.js:56  MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit
pg-copy-streams/index.js:56  MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
pg-copy-streams/index.js:56  MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
pg-copy-streams/index.js:56  MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
...
```
The problem seems to be that upon getting an error, pg-copy-streams doesn't do any cleanup, so each retry involves adding more and more listeners to the connection object.

I was able to solve this problem by copying the `handleCommandComplete()` cleanup code into `handleError()`, like so:
```
CopyStreamQuery.prototype.handleError = function(e) {
  // we delay the _flush cb so that the 'end' event is
  // triggered after CommandComplete
  this.cb_flush()

  // unpipe from connection
  this.unpipe(this.connection.stream)
  this.connection = null

  this.emit('error', e)
}
```
I'm not however sure whether this is the right or preferred way of dealing with this (duplicate code and all) so rather than submit a PR I'm putting it here as an issue.  Hopefully it's something that can be fixed fairly easily.

**Comment by jeromew** [comment]
Hello,

Thanks for your detailed report on this problem of leaking listeners in the case of errors.

I think that the error handling is not very well tested in the test suite and that there are probably many things to fix.

I'll try and reproduce the leak in a test. Do you remember what type of errors in the data you had to trigger the errors ?

**Comment by sign0** [comment]
Personally I have the same problem with violated primary keys ... And I also have a problem to listen correctly to the end event of a COPY FROM (piped) ... :(

I do not know if you know this tool (https://github.com/timescale/timescaledb-parallel-copy), it is for now my alternative until this package is a little more stable for an environment of production .. :)

**Comment by jeromew** [comment]
there have been big changes in the library and 4.0.0 was published.
hopefully it fixes the issues mentioned here.
itf you are still using the module feel free to open a new issue with a way to reproduce your issue if you still have a problem
