### ISSUE TITLE
usage with stream.finished no longer working in node v12.16.1

### ISSUE THREAD

**Issue by shusson** [brianc/node-pg-copy-streams#89]
We previously used the following pattern:

```

    const copyStream = client.query(
        pgCopy.from(
            `COPY MY_TABLE FROM STDIN WITH (FORMAT 'csv')`
        )
    );

    const csv: string[] = getCsvStrings();

    const input = new Readable({
        objectMode: true,
        read() {
            const item = csv.shift();

            if (!item) {
                this.push(null);
            } else {
                this.push(`${item}\n`);
            }
        }
    });

    await pipeline(input, copyStream);
    await finished(copyStream);
```
In node 12.16.1, `await finished(copyStream);` now waits indefinitely. 

The pattern we used was based on the understanding that https://github.com/brianc/node-pg-copy-streams/issues/21 and https://github.com/brianc/node-pg-copy-streams/issues/86 would be solved by using nodes [finished](https://nodejs.org/dist/latest-v12.x/docs/api/stream.html#stream_stream_finished_stream_options_callback) method. Which was working until we recently upgraded to 12.16.1. Last known working version was 12.14.0, which we have reverted to now until we figure out how to fix this.

**Comment by shusson** [comment]
It looks like node keeps changing the behviour of the streams api e.g https://github.com/nodejs/node/issues/32032 https://github.com/nodejs/node/issues/29699.

For now we are going with something a lot simpler and as recommended in the readme:

```typescript
    await new Promise((resolve, reject) => {
        copyStream.on("error", reject);
        copyStream.on("end", resolve);
        input.on("error", reject);
        input.pipe(copyStream);
    });

```

**Comment by jeromew** [comment]
thanks for the report and finding a solution that works for you. This module is a bit particular because of how it needs to pipe into the postgres connection stream. It could probably be modified to have a more standard semantic but it needs work.

**Comment by jeromew** [comment]
@shusson I re-open this issue because I would be very grateful if you could test again with version 4.0.0 that was just published. It should behave correctly with the `finished` and `pipeline` API.

don't hesitate to tell me if you don't have time to do this or if you don't use this module anymore. Thank you

**Comment by shusson** [comment]
@jeromew our tests pass with 4.0.0 and using `pipeline` 💚.

Our code looks something like this now:
```typescript
    const copyStream = client.query(
        pgCopy.from(
            `COPY MY_TABLE FROM STDIN WITH (FORMAT 'csv')`
        )
    );

    const input = new Readable({
       ...
    });

    await pipeline(input, copyStream);
```

 Thanks for the update.
