### ISSUE TITLE
"Read ETIMEDOUT" on long copies.

### ISSUE THREAD

**Issue by drob** [brianc/node-pg-copy-streams#9]
I'm using both the `from` and `to` streams to pipe data around, and I occasionally get a `Read ETIMEDOUT` error on large copies. Is there anything I can to to make this more robust, beyond adding retry logic?

These show up for copies that take more than an hour. (The underlying query takes ~5 seconds. I'm moving a lot of data around, and it's all going through node.)

Using `FORMAT binary` might help speed this up, but I'm a little paranoid about using it. How robustly have you tested this module with binary copies, if at all?

**Comment by jeromew** [comment]
@drob can you share an update on this 2014 issue ? This kind of bug is interesting to drill on but hard to reproduce ;-) 

regarding binary, you could be interested by the https://github.com/jeromew/node-pg-copy-streams-binary module I published recently if you need to transform the data you are moving around.

**Comment by jeromew** [comment]
I close this for now (2014). you can also test 2.0.0 which has an improvement on copy-to that make it behave better wrt the node loop.
