### ISSUE TITLE
TypeError: stream.pipe is not a function

### ISSUE THREAD

**Issue by metalsheep** [brianc/node-pg-copy-streams#90]
```js
var {Pool} = require('pg');
var copyTo = require('pg-copy-streams').to;

var pool = new Pool({ connectionString: process.env.DATABASE_URL });

pool.connect(async function(err, client, done) {
  console.log('stuck...')
  var stream = pool.query(copyTo('COPY migrations TO STDOUT'));
  console.log(stream)
  stream.pipe(process.stdout);
});
```

Logs
```Promise { <pending> }
(node:91903) UnhandledPromiseRejectionWarning: TypeError: stream.pipe is not a function
    at PendingItem.callback (/Users/alexstrachan/src/arbiter/src/tasks/test.js:10:10)
    at Pool._acquireClient (/Users/alexstrachan/src/arbiter/node_modules/pg-pool/index.js:271:21)
    at client.connect (/Users/alexstrachan/src/arbiter/node_modules/pg-pool/index.js:234:21)
    at Connection.<anonymous> (/Users/alexstrachan/src/arbiter/node_modules/pg/lib/client.js:179:7)
    at Object.onceWrapper (events.js:286:20)
    at Connection.emit (events.js:203:15)
    at Socket.<anonymous> (/Users/alexstrachan/src/arbiter/node_modules/pg/lib/connection.js:125:12)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
(node:91903) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:91903) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Mostly copied from the documentation.
The problem is stream is not a stream, but instead a promise.  If you await said promise it hangs forever.

I tried also using the callback interface

```js
var stream = pool.query(copyTo('COPY migrations TO STDOUT'), [], () => console.log('here'));
```

stream is undefined and 'here' will never log.

node 10.19.0 (also 12.14.1)
pg 7.8.2
node-pg-copy-streams 2.2.2

**Comment by metalsheep** [comment]
Debugging a little more this runs absolutely fine as
```var {Client} = require('pg');
var copyTo = require('pg-copy-streams').to;

var pool = new Client({ connectionString: process.env.DATABASE_URL });

pool.connect(async function(err, client, done) {
  console.log('stuck...')
  var stream = pool.query(copyTo('COPY migrations TO STDOUT'));
  console.log(stream)
  stream.pipe(process.stdout);
});
```
And the example code from pg QueryStream also fails to run with Pool, so I suspect this is an upstream issue with pg.

However, to anyone else having this issue - just use Client instead of Pool until it's sorted?

**Comment by jeromew** [comment]
Hello thanks for the report.
I suspect that Pool.query has a specific shortcoming in the current case.  in https://node-postgres.com/api/pool#pool.query it states

> Often we only need to run a single query on the database, so as convenience the pool has a method to run a query on the first available idle client and return its result.

I don't think Pool.query accepts Submittable as Client.query does but you would have to dig into the code to check that. cf Submittable part on https://node-postgres.com/api/client#client.query

**Comment by metalsheep** [comment]
I don't actually need the pool functionality in this case, it's just the example in the documentation has you use Pool so it took some debugging to get the example running.

**Comment by jeromew** [comment]
Reading again this issue, I think that in your original code

    var stream = pool.query(copyTo('COPY migrations TO STDOUT'));

should be

    var stream = client.query(copyTo('COPY migrations TO STDOUT'));

indeed there are 2 usage of pool :


1. pool.connect calls a callback with an available client and you can query on this client with client.query
2. pool.query does the 2 operations of (1) in one line.

so
````js
pool.connect(async function(err, client, done) {
  var stream = pool.query(copyTo('COPY migrations TO STDOUT'));
````
is a bug.

I'll close this for now. Don't hesitate to re-open this does not fix your issue
