### ISSUE TITLE
Support parameterised queries

### ISSUE THREAD

**Issue by ab-pm** [brianc/node-pg-copy-streams#92]
Hi,
I was wondering why there is no way to pass parameters into a query with this module. Is this a fundamental limitation of Postgres (I was not sure after reading https://postgrespro.com/list/thread-id/1893680), or is it just a missing feature?

**Comment by jeromew** [comment]
Hello,
in the thread you mention, I cannot find a message that would say that this has been implemented.

The main conclusion I read is :

> Bottom line is that there's a pretty large can of worms hiding under
> this, and I am not eager to open it.
>         regards, tom lane

In the documentation for "PREPARE" on pg12 it says https://www.postgresql.org/docs/current/sql-prepare.html

```
PREPARE name [ ( data_type [, ...] ) ] AS statement
statement: Any **SELECT, INSERT, UPDATE, DELETE, or VALUES** statement.
```

I may be wrong but I think your only option is to find a library that does a kind of prepared statement with placeholders client side with something like [pg-format](https://github.com/datalanche/node-pg-format)

**Comment by ab-pm** [comment]
@jeromew I was not certain whether that thread was only about `PREPARE`  statements or whether it also is about parameter handling in normal queries. But I suppose you're right…
